# Generated by Django 5.0.6 on 2024-06-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_comment_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='forum_post',
            old_name='author',
            new_name='creator',
        ),
    ]
