# Generated by Django 3.2.23 on 2024-05-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_and_nes', '0003_auto_20240510_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.FileField(default='default_video.jpg', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
